### ISSUE TITLE
Leading spaces in cells

### ISSUE THREAD

**Issue by shibormot** [tabulapdf/tabula-extractor#107]
Hello Jeremy, for my task I need to keep leading spaces in cells, on first line of text if text in cell is multiline. Would you please tell me where in the code lives the logic removing that spaces. If it is easy to turn it off your answer will save me some time because I am very new to ruby :)

By the way, may be include option for that?

Ivan

**Comment by jeremybmerrill** [comment]
`.strip` [here](https://github.com/tabulapdf/tabula-extractor/blob/32c73324327ff8c248613635512068ba78595667/lib/tabula/entities/cell.rb#L41) is what removes whitespace from cell text. I'm curious what your task is, since someone using significant whitespace in a table in a PDF is... creating quite a challenge for you.

I'd caution you, however, that [tabula-java](https://github.com/tabulapdf/tabula-java) is meant to supersede tabula-extractor shortly, so if Java's more your cup of tea, I'd recommend using that instead.

**Comment by shibormot** [comment]
It is pdfs from ministry of building of Russia. I'd like to parse them to fill dictionaries of materials that can be used when implementing goverment contracts. There are commercial software with this dictionaries inside, but it is not so convenient to integrate it with our bussines apps. Spaces are used to indicate that items are in subgroups, while opposite indicates standalong items. For example http://www.minstroyrf.ru/upload/iblock/0c2/fssts_03-prikaz.pdf 

There are other ugly files from our goverment: http://www.minstroyrf.ru/upload/iblock/e45/gsn-vodosnabzh.-i-kanaliz..doc.pdf 

But the second file is not my problem for now at least)

Thank you very much for both hints

**Comment by jeremybmerrill** [comment]
PDFs do not, generally, contain spaces. Instead, they position text in different places. Tabula does not add leading spaces in cases like your PDF, so I think you're going to have to find another solution than depending on the indentation of text to distinguish standalone/grouped items.
